### ISSUE TITLE
Can I haz GNU Taler support?

### ISSUE THREAD

**Issue by BenPortner** [stustapay/stustapay#303]
Dear Stustapay developers,

First off: Kudos to this great piece of software. I used it at last year's Stustaculum and it worked flawlessly. You did a great job developing it and an even greater job publishing it openly for everyone to use!

To my question / feature request: Would it be possible to implement support for [GNU Taler](https://taler.net/en/principles.html) in Stustapay? GNU Taler is a payment system that allows privacy-friendly transactions via NFC or QR code. It's main selling point (from my point of view) is that transactions cannot be traced back to the paying party (Nobody can tell that I bought 10 beers at the Bierkarussell. Unless I drink them all. Then it's easy to tell...). Generally, GNU Taler aims to become a payment solution for the broad public and supported by all major retail banks. However, they are now in the pilot phase and first trials are running as a payment system for events (e.g. LugCamp 2024). Maybe Stustaculum 2025 could be one of them? I definitely believe their cause is worth supporting! :)

Cheers
Ben

**Comment by TheJJ** [comment]
Hi Ben! How would you imagine taler integration would work? that people can top up their balance not using cash and cards but also taler? We have a distinct account for each user, which could - in theory - be linked to a taler account where money is deducted.

I fear though our time investments for such features are quite limited, since we focus on the general usability for our guests and the team, so we very likely are not going to implement this any time soon. But of course if for some event of yours you extend the functionality, you can surely add it and submit the patches to us.

If Taler takes over the world then we will for sure be among the first to add support, right now it still seems rather experimental (and architecturally really complicated) to me (last saw an installation at cccamp 23).

Cheers  -- JJ

**Comment by BenPortner** [comment]
Hello @TheJJ 

thanks for your fast reply! Please find my answers below.

> How would you imagine taler integration would work? that people can top up their balance not using cash and cards but also taler? We have a distinct account for each user, which could - in theory - be linked to a taler account where money is deducted.

What I imagined was more like the current system (I can top up my wallet using cash or cards) but with the added benefit of having anonymity when buying something on the event - i.e. transactions on the festival would be made using the Taler payment system.

> I fear though our time investments for such features are quite limited, since we focus on the general usability for our guests and the team, so we very likely are not going to implement this any time soon. [...] right now it still seems rather experimental (and architecturally really complicated) to me (last saw an installation at cccamp 23).

I understand that time is a hard constraint and there is no way to argue around this. However, I wouldn't be surprised if the GNU Taler folks are willing to help, both with the integration into StustaPay and with the administration during the event. After all, they are an open team with an ambitious agenda, as well. I could inquire this on your behalf if time is all that is blocking right now?

**Comment by TheJJ** [comment]
sure, I'd be interested in what the Taler team would say to such an application as ours :)

**Comment by TheJJ** [comment]
we've been contacted by email, i'll close this for now.
